// editor/src/components/MainMenu.vue
<template>
	<div class="main-menu-component" ref="mainMenu">
		<div class="mb-0 fill-dark text-light is-shadowed" style="z-index: 1000; border-bottom: 1px solid black;">
			<div class="">
				<ul class="nav nav-menu">
					<div class="nav-left">
						<ul class="nav-item">
							<li class="menu-item item-has-children">
								<div role="button" tabindex="0" class="dropdown-toggle" @click="toggleDropdown($event)">File</div>
								<ul class="sub-menu">
									<li>
										<div role="button" tabindex="0" @click="$emit('on-new-project-clicked')">New project</div>
									</li>
									<li>
										<div role="button" tabindex="0" @click="$emit('on-open-project')">Open project</div>
									</li>
									<li>
										<div role="button" tabindex="0" @click="$emit('on-new-scene-clicked')">New scene</div>
									</li>
									<li>
										<div role="button" tabindex="0" @click="$emit('on-open-scene-config')">Scene configuration</div>
									</li>
									<li>
										<div role="button" tabindex="0" @click="$emit('on-open-settings')">Settings</div>
									</li>
								</ul>
							</li>
							<li class="menu-item item-has-children">
								<div role="button" tabindex="0" class="dropdown-toggle" @click="toggleDropdown($event)">View</div>
								<ul class="sub-menu">
									<li>
										<div>
											<input type="checkbox" id="toggle-layer-highlighting" name="toggle-layer-highlighting" class="chk-highlight-current-layer" />
											<label for="toggle-layer-highlighting">Toggle layer highlighting</label>
										</div>
									</li>
								</ul>
							</li>
							<li class="menu-item">
								<div role="button" tabindex="0" y-ref="/options">Options</div>
							</li>
						</ul>
					</div>
					<!-- <div class="nav-center" v-if="project && project.engineConfig">{{ project.engineConfig.name }} <span>/</span> Yak Engine</div> -->
					<div class="nav-right">
						<ul class="nav-item">
							<li class="menu-item">
								<div role="button" tabindex="0" @click="minimize()">
									<i class="fa fa-window-minimize"></i>
								</div>
							</li>
							<li class="menu-item">
								<div role="button" tabindex="0" @click="toggleWindowState()">
									<i class="fa fa-window-restore"></i>
								</div>
							</li>
							<li class="menu-item">
								<div role="button" tabindex="0" @click="close()">
									<i class="fa fa-close fa-lg text-red"></i>
								</div>
							</li>
						</ul>
					</div>
				</ul>
			</div>
		</div>
	</div>
</template>

<script lang="ts">
import { Component, Emit, Prop, Vue, Watch } from 'vue-property-decorator';

import EngineConfig from '../../../engine/src/engine-config';

@Component({})
export default class MainMenu extends Vue {
	constructor() {
		super();

		document.addEventListener('click', (event: MouseEvent) => {
			let mainMenu = <HTMLElement>this.$refs.mainMenu;

			if (!mainMenu.contains(<HTMLElement>event.target)) {
				mainMenu.querySelectorAll('.menu-item.item-has-children.expanded').forEach((expandedMenuItem) => {
					expandedMenuItem.classList.remove('expanded');
				});
			}
		});
	}

	toggleWindowState(): void {
		let browserWindow = (window as any).electron.getCurrentWindow();

		if (browserWindow.isMaximized()) {
			this.minimize();
		} else {
			this.maximize();
		}
	}

	maximize(): void {
		(window as any).electron.getCurrentWindow().maximize();
	}

	minimize(): void {
		(window as any).electron.getCurrentWindow().minimize();
	}

	close(): void {
		(window as any).electron.getCurrentWindow().close();
	}

	toggleDropdown(event: MouseEvent) {
		let target = <HTMLElement>event.target;

		if (target.parentElement.classList.contains('item-has-children')) {
			target.parentElement.classList.add('expanded');
		}
	}
}
</script>

<style scoped lang="scss">
// .main-menu-component {
//     -webkit-app-region: drag
// }

.menu-item {
	cursor: pointer;
}
</style>

// editor/src/app/components/layout/main-menu/main-menu.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-main-menu',
  templateUrl: './main-menu.component.html',
  styleUrls: ['./main-menu.component.scss']
})
export class MainMenuComponent {
	constructor() {
		document.addEventListener('click', (event: MouseEvent) => {
			// let mainMenu = <HTMLElement>this.$refs.mainMenu;

			// if (!mainMenu.contains(<HTMLElement>event.target)) {
			// 	mainMenu.querySelectorAll('.menu-item.item-has-children.expanded').forEach((expandedMenuItem) => {
			// 		expandedMenuItem.classList.remove('expanded');
			// 	});
			// }
		});
	}

	toggleWindowState(): void {
		let browserWindow = (window as any).electron.getCurrentWindow();

		if (browserWindow.isMaximized()) {
			this.minimize();
		} else {
			this.maximize();
		}
	}

	maximize(): void {
		(window as any).electron.getCurrentWindow().maximize();
	}

	minimize(): void {
		(window as any).electron.getCurrentWindow().minimize();
	}

	close(): void {
		(window as any).electron.getCurrentWindow().close();
	}

	toggleDropdown(event: MouseEvent) {
		let target = <HTMLElement>event.target;

		// if (target.parentElement.classList.contains('item-has-children')) {
		// 	target.parentElement.classList.add('expanded');
		// }
	}
}

<div class="main-menu-component" ref="mainMenu">
    <div class="mb-0 fill-dark text-light is-shadowed" style="z-index: 1000; border-bottom: 1px solid black;">
        <div class="">
            <ul class="nav nav-menu">
                <div class="nav-left">
                    <ul class="nav-item">
                        <li class="menu-item item-has-children">
                            <div role="button" tabindex="0" class="dropdown-toggle" (click)="toggleDropdown($event)">File</div>
                            <ul class="sub-menu">
                                <li>
                                    <!-- (click)="$emit('on-new-project-clicked')" -->
                                    <div role="button" tabindex="0">New project</div>
                                </li>
                                <li>
                                    <!-- (click)="$emit('on-open-project')" -->
                                    <div role="button" tabindex="0">Open project</div>
                                </li>
                            </ul>
                        </li>
                        <li class="menu-item item-has-children">
                            <div role="button" tabindex="0" class="dropdown-toggle" (click)="toggleDropdown($event)">Project</div>
                            <ul class="sub-menu">
                                <li>
                                    <!-- (click)="$emit('on-new-project-clicked')" -->
                                    <div role="button" tabindex="0">Scene configuration</div>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <!-- (click)="$emit('on-open-settings')" -->
                                    <div role="button" tabindex="0">Settings</div>
                                </li>
                            </ul>
                        </li>
                        <!-- <li class="menu-item item-has-children">
                            <div role="button" tabindex="0" class="dropdown-toggle" (click)="toggleDropdown($event)">View</div>
                            <ul class="sub-menu">
                                <li>
                                    <div>
                                        <input type="checkbox" id="toggle-layer-highlighting" name="toggle-layer-highlighting" class="chk-highlight-current-layer" />
                                        <label for="toggle-layer-highlighting">Toggle layer highlighting</label>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="menu-item">
                            <div role="button" tabindex="0" y-ref="/options">Options</div>
                        </li> -->
                    </ul>
                </div>
                <!-- <div class="nav-center" v-if="project && project.engineConfig">{{ project.engineConfig.name }} <span>/</span> Yak Engine</div> -->
                <div class="nav-right">
                    <ul class="nav-item">
                        <li class="menu-item">
                            <div role="button" tabindex="0" (click)="minimize()">
                                <i class="fa fa-window-minimize"></i>
                            </div>
                        </li>
                        <li class="menu-item">
                            <div role="button" tabindex="0" (click)="toggleWindowState()">
                                <i class="fa fa-window-restore"></i>
                            </div>
                        </li>
                        <li class="menu-item">
                            <div role="button" tabindex="0" (click)="close()">
                                <i class="fa fa-close fa-lg text-red"></i>
                            </div>
                        </li>
                    </ul>
                </div>
            </ul>
        </div>
    </div>
</div>
