// editor/src/app/components/inspector/collider/collider.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-collider',
  templateUrl: './collider.component.html',
  styleUrls: ['./collider.component.scss']
})
export class ColliderComponent {
  @Input()
	public inspectorComponentData: any;
}

<div class="collider-component" v-if="inspectorComponentData">
    <div class="checkbox">
      <input type="checkbox" id="isTrigger" name="isTrigger" [(ngModel)]="inspectorComponentData.isTrigger" />
      <label for="isTrigger">Is Trigger?</label>
    </div>
    
    <div class="transform-values">
      <div class="transform-value flex flex-r align-items-center">
        <div class="form-label text-small">X</div>
        <input type="text" name="transform-x" [(ngModel)]="inspectorComponentData.transform.x" />
      </div>
      <div class="transform-value flex flex-r align-items-center">
        <div class="form-label text-small">Y</div>
        <input type="text" name="transform-y" [(ngModel)]="inspectorComponentData.transform.y" />
      </div>
      <div class="transform-value flex flex-r align-items-center">
        <div class="form-label text-small">W</div>
        <input type="text" name="transform-width" [(ngModel)]="inspectorComponentData.transform.width" />
      </div>
      <div class="transform-value flex flex-r align-items-center">
        <div class="form-label text-small">H</div>
        <input type="text" name="transform-height" [(ngModel)]="inspectorComponentData.transform.height" />
      </div>
    </div>
  </div>

// editor/src/components/Inspector/ColliderComponent.vue
<template>
  <div class="collider-component" v-if="inspectorComponentData">
    <div class="checkbox">
      <input type="checkbox" id="isTrigger" name="isTrigger" v-model="inspectorComponentData.isTrigger" />
      <label for="isTrigger">Is Trigger?</label>
    </div>
    
    <div class="transform-values">
      <div class="transform-value flex flex-r align-items-center">
        <div class="form-label text-small">X</div>
        <input type="text" v-model="inspectorComponentData.transform.x" />
      </div>
      <div class="transform-value flex flex-r align-items-center">
        <div class="form-label text-small">Y</div>
        <input type="text" v-model="inspectorComponentData.transform.y" />
      </div>
      <div class="transform-value flex flex-r align-items-center">
        <div class="form-label text-small">W</div>
        <input type="text" v-model="inspectorComponentData.transform.width" />
      </div>
      <div class="transform-value flex flex-r align-items-center">
        <div class="form-label text-small">H</div>
        <input type="text" v-model="inspectorComponentData.transform.height" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">

import { Component, Prop, Vue } from "vue-property-decorator";

@Component
export default class ColliderComponent extends Vue {
  @Prop() inspectorComponentData: string;
};

</script>

<style>

</style>
