// editor/src/app/components/inspector/material/material.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-material',
  templateUrl: './material.component.html',
  styleUrls: ['./material.component.scss']
})
export class MaterialComponent {
  @Input()
	public inspectorComponentData: any;
}

<div class="material-component">
    <input class="fill-style" type="text" name="fillStyle" [(ngModel)]="inspectorComponentData.fillStyle" />
</div>

// editor/src/components/Inspector/MaterialComponent.vue
<template>
  <div class="material-component">
    <input class="fill-style" type="text" v-model="inspectorComponentData.fillStyle" />
  </div>
</template>

<script lang="ts">

import { Component, Prop, Vue } from "vue-property-decorator";

@Component
export default class MaterialComponent extends Vue {
  @Prop() inspectorComponentData: string;
};

</script>

<style>
.fill-style {
  width: 50%;
}
</style>
