// editor/src/app/components/inspector/sprite-renderer/sprite-renderer.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-sprite-renderer',
  templateUrl: './sprite-renderer.component.html',
  styleUrls: ['./sprite-renderer.component.scss']
})
export class SpriteRendererComponent {
  @Input()
	public inspectorComponentData: any;
}

<div class="sprite-component">
    Not yet implemented
</div>

// editor/src/components/Inspector/SpriteRendererComponent.vue
<template>
  <div class="sprite-component">
    Not yet implemented
  </div>
</template>

<script lang="ts">

import { Component, Prop, Vue } from "vue-property-decorator";

@Component
export default class SpriteRendererComponent extends Vue {
  @Prop() inspectorComponentData: string;
};

</script>

<style>

</style>
