// editor/src/app/components/inspector/tag/tag.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-tag',
  templateUrl: './tag.component.html',
  styleUrls: ['./tag.component.scss']
})
export class TagComponent {
  @Input()
	public inspectorComponentData: any;
}

<div class="tag-component">
    <input class="tag-name" type="text" name="tag-name" [(ngModel)]="inspectorComponentData.name" />
  </div>

// editor/src/components/Inspector/TagComponent.vue
<template>
  <div class="tag-component">
    <input class="tag-name" type="text" v-model="inspectorComponentData.name" />
  </div>
</template>

<script lang="ts">

import { Component, Prop, Vue } from "vue-property-decorator";

@Component
export default class TagComponent extends Vue {
  @Prop() inspectorComponentData: string;
};

</script>

<style>
.tag-name {
  width: 50%;
}
</style>
