// editor/src/app/components/directory-dialog/directory-dialog.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: '[app-directory-dialog]',
  templateUrl: './directory-dialog.component.html',
  styleUrls: ['./directory-dialog.component.scss']
})
export class DirectoryDialogComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  async selectTargetPath(): Promise<void> {
    // let results: OpenDialogReturnValue = await window.electron.dialog.showOpenDialog({
    //     properties: ['openDirectory']
    // });

    // if (results) {
    //   this.$emit('on-directory-selected', results.filePaths[0])
    // }
  }
}

<div class="directory-dialog-component">
    <button type="button" (click)="selectTargetPath()">Browse</button>
  </div>

// editor/src/components/DirectoryDialog.vue
<template>
  <div class="directory-dialog-component">
    <button type="button" @click="selectTargetPath()">Browse</button>
  </div>
</template>

<script lang="ts">

import { Component, Prop, Vue } from 'vue-property-decorator';

import { app, OpenDialogReturnValue } from "electron/main";

@Component
export default class Default extends Vue {

  async selectTargetPath(): Promise<void> {
    let results: OpenDialogReturnValue = await window.electron.dialog.showOpenDialog({
        properties: ['openDirectory']
    });

    if (results) {
      this.$emit('on-directory-selected', results.filePaths[0])
    }
  }
};

</script>

<style scoped lang="scss">

</style>
