// editor/src/app/components/inspector/inspector.component.ts
import { Component, OnInit } from '@angular/core';
import MaterialComponent from '../../../../../engine/src/components/MaterialComponent';
import Entity from '../../../../../engine/src/models/entity';
import { BaseComponent } from '../base.component';

@Component({
  selector: '[app-inspector]',
  templateUrl: './inspector.component.html',
  styleUrls: ['./inspector.component.scss']
})
export class InspectorComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

	/**
	 * All of the 
	 */
	componentInstances: Array<BaseComponent> = [];

	isAddingComponent: boolean = false;

	get componentNames(): string[] {
		// return Constants.componentTypes.map((componentType) => componentType.name);
		return [];
	}

	save(): void {
		// this.entity.addComponent(new MaterialComponent('white', 0));
		// this.scene.name = 'test';
	}

	/**
	 * When the currently selected entity changes ensure we update the inspector with the 
	 * components associated with the given entity.
	 */
	// @Watch('entity', { immediate: true })
	onEntityChanged(newValue: any, oldValue: any): void {
		if(newValue) {
			// this.componentInstances = EntityManager.getInstance().getComponents(this.entity);
		}
	}
}

<div class="inspector-component">
    <div class="scene-editor-panel-header">
        <span class="title"><i class="fa fa-cube fa-lg"></i> Inspector</span>
        <div class="actions">
            <button type="button" (click)="isAddingComponent = true">
                <i class="fa fa-plus"></i>
            </button>
        </div>
    </div>
    <div class="inspector-body">
        <ng-container *ngFor="let componentInstance of componentInstances">
            <!-- <div app-component-template [instance]="componentInstance"></div> -->
        </ng-container>
    </div>
    <!-- <modal v-if="isAddingComponent" :is-open="isAddingComponent" :title="'Add new component'" :modal-size="'modal-sm'" @on-modal-saved="save()" @on-modal-closed="isAddingComponent = false">
        <div class="entity-form">
            <select>
                <option *ngFor="let componentName in componentNames">
                    {{ componentName.split('Component')[0].split(/(?=[A-Z])/).join(' ') }}
                </option>
            </select>
        </div>
    </modal> -->
</div>

// editor/src/components/Inspector.vue
<template>
	<div class="inspector-component">
		<div class="scene-editor-panel-header">
			<span class="title"><i class="fa fa-cube fa-lg"></i> Inspector</span>
			<div class="actions">
				<button type="button" @click="toggleAddMode()">
					<i class="fa fa-plus"></i>
				</button>
			</div>
		</div>
		<div class="inspector-body">
			<component-template v-for="(entityComponent, index) in entityComponents" :key="index" :entity-component="entityComponent">
				
			</component-template>
		</div>
		<modal v-if="isAddingComponent" :is-open="isAddingComponent" :title="'Add new component'" :modal-size="'modal-sm'" @on-modal-saved="save()" @on-modal-closed="isAddingComponent = false">
			<div class="entity-form">
				<div class="form-section">
					<div class="form-label">Component</div>
					<select>
						<option v-for="(componentName, index) in componentNames" :key="index">
							{{ componentName }}
						</option>
					</select>
				</div>
			</div>
		</modal>
	</div>
</template>

<script lang="ts">
import { Component, Prop, Vue, Watch } from 'vue-property-decorator';

import ComponentTemplate from './Inspector/ComponentTemplate.vue';
import Modal from './Modal.vue';
import { component } from 'vue/types/umd';

import Entity from '../../../engine/src/components/entity';
import Constants from '../../../engine/src/constants';
import { constants } from 'fs-extra';
import { State } from 'vuex-class';
import SceneConfig from '../../../engine/src/models/scene-config';
import EntityManager from '../../../engine/src/components/EntityManager';
import EngineMaterialComponent from '../../../engine/src/components/material/MaterialComponent';

@Component({
	components: {
		Modal,
		ComponentTemplate
	}
})
export default class Inspector extends Vue {
	@State entity: Entity;
	@State scene: SceneConfig;

	entityComponents: Array<any> = [];

	isAddingComponent: boolean = false;

	get componentNames(): string[] {
		return Constants.componentNames;
	}

	bootstrapAvailableComponents(): void {
		this.entityComponents = Constants.componentNames.filter((componentName) => {
			return this.entity.getComponent<any>(componentName) !== null;
		})
		.map((componentName) => {
			let componentInstance = this.entity.getComponent<any>(componentName);

			return {
				componentInstance: componentInstance,
				componentName: componentName
			};
		});
	}

	toggleAddMode(): void {
		this.isAddingComponent = true;
	}

	save(): void {
		this.entity.addComponent(new EngineMaterialComponent('white', 0));
		this.scene.name = 'test';
	}

	@Watch('entity', { immediate: true })
	onEntityChanged(newValue: any, oldValue: any): void {
		if(newValue) {
			this.bootstrapAvailableComponents();
		}
	}
}
</script>

<style lang="scss" scoped>
.inspector-component {
	flex: 1;
	
	.inspector-body {
	padding: 15px;
	}
}
</style>
