// editor/src/app/components/project-hierarchy/project-hierarchy.component.ts
import { Component, OnInit } from '@angular/core';
import { Project } from 'src/app/models/project';

@Component({
  selector: '[app-project-hierarchy]',
  templateUrl: './project-hierarchy.component.html',
  styleUrls: ['./project-hierarchy.component.scss']
})
export class ProjectHierarchyComponent implements OnInit {
  public project?: Project;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="project-hierarchy-component" *ngIf="project">
    <div class="scene-editor-panel-header is-shadowed">
        <span class="title">Project Hierarchy</span>
        <div class="actions"></div>
    </div>
    <div class="tree-component">
        <div app-tree [items]="project.tree"></div>
    </div>
</div>

// editor/src/components/ProjectHierarchy.vue
<template>
	<div class="project-hierarchy-component" v-if="project">
		<div class="scene-editor-panel-header is-shadowed">
			<span class="title">Project Hierarchy</span>
			<div class="actions"></div>
		</div>
		<div class="tree-component">
			<tree :items="project.tree"></tree>
		</div>
	</div>
</template>

<script lang="ts">
import { Component, Prop, Vue, Watch } from 'vue-property-decorator';
import { State } from 'vuex-class';

import Tree from './Tree.vue';

@Component({
	components: {
		Tree
	}
})
export default class ProjectHierarchy extends Vue {
	@State project;
}
</script>

<style lang="scss" scoped>
.project-hierarchy-component {
	flex: 1;
}
</style>
