// editor/src/app/components/scene/scene-information/scene-information.component.ts
import { Component, OnInit } from '@angular/core';
import { StateService } from 'src/app/services/state.service';
import Scene from '../../../../../../engine/src/models/scene';

@Component({
  selector: 'app-scene-information',
  templateUrl: './scene-information.component.html',
  styleUrls: ['./scene-information.component.scss']
})
export class SceneInformationComponent {
  public scene!: Scene;

  public sceneCopy?: Scene = undefined;

  constructor(private _stateService: StateService) {
    this._stateService.scene$.subscribe((scene) => {

    })
  }

  // @Watch('scene')
  onSceneChanged(newValue: Scene, oldValue: Scene): void {
    if(newValue) {
      this.sceneCopy = Object.assign({}, this.scene);
    }
  }
}

<div class="scene-information-component" v-if="scene">
    <div class="form-section">
        <div class="form-label text-small">Tile size</div>
        <input class="tag-name" type="text" v-model.number="sceneCopy.tileSize" />
    </div>

    <div class="form-section">
        <div class="form-label text-small">Rows</div>
        <input class="tag-name" type="text" v-model.number="sceneCopy.rows" />
    </div>

    <div class="form-section">
        <div class="form-label text-small">Columns</div>
        <input class="tag-name" type="text" v-model.number="sceneCopy.columns" />
    </div>
</div>

// editor/src/components/SceneInformation.vue
<template>
	<div class="scene-information-component" v-if="scene">
		<div class="form-section">
			<div class="form-label text-small">Tile size</div>
			<input class="tag-name" type="text" v-model.number="sceneCopy.tileSize" />
		</div>

		<div class="form-section">
			<div class="form-label text-small">Rows</div>
			<input class="tag-name" type="text" v-model.number="sceneCopy.rows" />
		</div>

		<div class="form-section">
			<div class="form-label text-small">Columns</div>
			<input class="tag-name" type="text" v-model.number="sceneCopy.columns" />
		</div>
	</div>
</template>

<script lang="ts">
import { Component, Prop, Vue, Watch } from 'vue-property-decorator';
import { Action, State } from 'vuex-class';

import Scene from '../../../engine/src/models/scene';

@Component
export default class SceneInformation extends Vue {
  @State scene;
  @Action public setScene;

  sceneCopy: Scene = null;

  @Watch('scene')
  onSceneChanged(newValue: Scene, oldValue: Scene): void {
    if(newValue) {
      this.sceneCopy = Object.assign({}, this.scene);
    }
  }
}
</script>

<style scoped lang="scss">
.scene-information-component {
	flex: 1;
}
</style>
