// editor/src/components/SceneToolbar.vue
<template>
	<div class="scene-toolbar-component">
		<ul class="nav nav-menu mb-0 fill-dark text-white is-shadowed" style="z-index: 500; border-bottom: 1px solid black">
			<div class="nav-left">
				<ul class="nav-item">
					<li :class="{ selected: transformMode === 0 }">
						<div role="button" class="btn-toolbar-item" tabindex="0" @click="onSetTransformMode(0)" title="Position">
							<i class="fa fa-arrows"></i>
						</div>
					</li>
					<li :class="{ selected: transformMode === 1 }">
						<div role="button" class="btn-toolbar-item" tabindex="0" @click="onSetTransformMode(1)" title="Scale">
							<i class="fa fa-sliders"></i>
						</div>
					</li>
					<li :class="{ selected: transformMode === 2 }">
						<div role="button" class="btn-toolbar-item" tabindex="0" @click="onSetTransformMode(2)" title="Rotate">
							<i class="fa fa-refresh"></i>
						</div>
					</li>
				</ul>
			</div>
			<div class="nav-right">
				<ul class="nav-item">
					<li class="menu-item">
						<div role="button" tabindex="0" class="btn-play" @click="setIsPlayMode(true)">
							<i class="fa fa-play text-green-darken-2 mr-default"></i>
							<span class="text-white">PLAY</span>
						</div>
					</li>
				</ul>
			</div>
		</ul>
	</div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { Action, State } from 'vuex-class';
import { TransformMode } from '../enums/TransformMode';

@Component
export default class SceneToolbar extends Vue {
    // Store state.
    @State transformMode;

    // Store actions.
	@Action setTransformMode;
	@Action setIsPlayMode;

    onSetTransformMode(transformMode: TransformMode): void {
        this.setTransformMode(transformMode);
    }
}
</script>

<style scoped lang="scss"></style>

// editor/src/app/components/scene/scene-toolbar/scene-toolbar.component.ts
import { Component, OnInit } from '@angular/core';
import { TransformMode } from 'src/app/enums/transform-mode';
import { StateService } from 'src/app/services/state.service';

@Component({
  selector: '[app-scene-toolbar]',
  templateUrl: './scene-toolbar.component.html',
  styleUrls: ['./scene-toolbar.component.scss']
})
export class SceneToolbarComponent implements OnInit {
    public transformMode: TransformMode = TransformMode.MOVE;

constructor(private _stateService: StateService) {
        
    }

    public ngOnInit(): void {
        this._stateService.transformMode$.subscribe((transformMode: TransformMode) => this.transformMode = transformMode);
    }

    onSetTransformMode(transformMode: TransformMode): void {
        this._stateService.setTransformMode(transformMode);
    }

    public setIsPlayMode(isPlayMode: boolean): void {
        // TODO: Save on state.
    }
}

<div class="scene-toolbar-component">
    <ul class="nav nav-menu mb-0 fill-dark text-white is-shadowed" style="z-index: 500; border-bottom: 1px solid black">
        <div class="nav-left">
            <ul class="nav-item">
                <li [class]="{ selected: transformMode === 0 }">
                    <div role="button" class="btn-toolbar-item" tabindex="0" (click)="onSetTransformMode(0)" title="Position">
                        <i class="fa fa-arrows"></i>
                    </div>
                </li>
                <li [class]="{ selected: transformMode === 1 }">
                    <div role="button" class="btn-toolbar-item" tabindex="0" (click)="onSetTransformMode(1)" title="Scale">
                        <i class="fa fa-sliders"></i>
                    </div>
                </li>
                <li [class]="{ selected: transformMode === 2 }">
                    <div role="button" class="btn-toolbar-item" tabindex="0" (click)="onSetTransformMode(2)" title="Rotate">
                        <i class="fa fa-refresh"></i>
                    </div>
                </li>
            </ul>
        </div>
        <div class="nav-right">
            <ul class="nav-item">
                <li class="menu-item">
                    <div role="button" tabindex="0" class="btn-play" (click)="setIsPlayMode(true)">
                        <i class="fa fa-play text-green-darken-2 mr-default"></i>
                        <span class="text-white">PLAY</span>
                    </div>
                </li>
            </ul>
        </div>
    </ul>
</div>
